# Generated by Django 4.2.5 on 2023-11-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
