# Generated by Django 4.2.5 on 2023-11-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0002_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Fixed Deposit', 'Fixed Deposit'), ('Recurring Deposit', 'Recurring Deposit'), ('SIP', 'SIP'), ('Investment', 'Investment')], max_length=20)),
                ('description', models.TextField()),
                ('duration_of_years', models.PositiveIntegerField()),
            ],
        ),
    ]
