# Generated by Django 4.2.5 on 2023-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0003_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtype',
            name='tax_type',
            field=models.CharField(default='Percentage', max_length=20),
        ),
    ]
