# Generated by Django 4.2.5 on 2023-11-08 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0004_alter_taxtype_tax_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='actual_stock',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Fuel', 'Fuel')], default='Stationary', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apkapp.supplier'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='batch_number',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
