# Generated by Django 4.2.6 on 2023-11-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0006_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
