# Generated by Django 4.2.6 on 2023-11-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0008_mutualfund_delete_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutualFund',
        ),
    ]
