# Generated by Django 4.2.6 on 2023-11-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0011_mutualfund_product_type_mutualfund_query_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=100, unique=True)),
                ('investor_name', models.CharField(max_length=255)),
                ('investor_pan', models.CharField(max_length=10)),
                ('investor_dob', models.DateField()),
                ('investor_email', models.EmailField(max_length=254)),
                ('investor_mobile', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('roi', models.FloatField()),
                ('tenure_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly')], max_length=20)),
                ('tenure_duration', models.CharField(choices=[('annually', 'Annually'), ('cumulative', 'Cumulative')], max_length=20)),
                ('nominee_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
