# Generated by Django 4.2.6 on 2023-11-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0012_fixeddeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=100, unique=True)),
                ('proposer_name', models.CharField(max_length=255)),
                ('proposer_dob', models.DateField()),
                ('proposer_pan', models.CharField(max_length=20)),
                ('life_assured_name', models.CharField(max_length=255)),
                ('life_assured_dob', models.DateField()),
                ('life_assured_pan', models.CharField(max_length=20)),
                ('life_assured_aadhar_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('plan_name', models.CharField(max_length=255)),
                ('ppt', models.CharField(max_length=10)),
                ('pt', models.CharField(max_length=10)),
                ('nominee_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('premium_frequency', models.CharField(max_length=50)),
            ],
        ),
    ]
