# Generated by Django 4.2.6 on 2023-11-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0015_generalinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinsurance',
            name='product_type',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Product Type'),
        ),
    ]
