# Generated by Django 4.2.6 on 2023-11-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0016_generalinsurance_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinsurance',
            name='product_type',
        ),
    ]
