# Generated by Django 4.2.6 on 2023-11-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0017_remove_generalinsurance_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=100, unique=True)),
                ('investor_name', models.CharField(max_length=255, verbose_name='Investor Name')),
                ('pan_number', models.CharField(max_length=10, verbose_name='PAN Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('scheme_name', models.CharField(max_length=255, verbose_name='Scheme Name')),
                ('nominee_name', models.CharField(max_length=255, verbose_name='Nominee Name')),
                ('roi', models.CharField(max_length=255, verbose_name='ROI')),
                ('frequency', models.CharField(max_length=255, verbose_name='Frequency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
            ],
        ),
    ]
