# Generated by Django 4.2.6 on 2023-11-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0019_nps'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='nps',
            name='insurance_companies',
            field=models.ManyToManyField(to='apkapp.insurancecompany'),
        ),
    ]
