# Generated by Django 4.2.6 on 2023-11-13 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0020_insurancecompany_nps_insurance_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='nps',
            name='query_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
