# Generated by Django 4.2.6 on 2023-11-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0021_nps_query_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nps',
            name='query_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
