# Generated by Django 4.2.6 on 2023-11-13 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0022_alter_nps_query_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nps',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
