# Generated by Django 4.2.6 on 2023-11-13 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0023_nps_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nps',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
