# Generated by Django 4.2.6 on 2023-11-13 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0024_alter_nps_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonds',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
