# Generated by Django 4.2.6 on 2023-11-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0026_fixeddeposit_created_at_generalinsurance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nps',
            name='product_type',
            field=models.CharField(default='NPS', max_length=255),
        ),
    ]
