# Generated by Django 4.2.6 on 2023-11-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0027_nps_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nps',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
