# Generated by Django 4.2.6 on 2023-11-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0028_alter_nps_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonds',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
