# Generated by Django 4.2.6 on 2023-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapp', '0029_bonds_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalinsurance',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lifeinsurance',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfund',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
